### ISSUE TITLE
Is iggy embeddable? Can it be used as a library?

### ISSUE THREAD

**Issue by Froidoh** [iggy-rs/iggy#1007]
Hey!

I need a pub/sub system for a rust project and wondered whether iggy can be embedded in that application, so whether it has the ability to be used as a library.

Thanks for taking your time to answer!

**Comment by hubcio** [comment]
hey, in short, iggy consists of couple of parts:
- iggy-server - like the name suggests, it runs the server to which log stream is sent / is read from
**- sdk - this is library that is used by clients, it has API that allows you to interact with server (send messages, poll messages and so on) - this is delivered via `crates.io` - so this is -embeddable-**
- iggy-cli - neat command line utility mainly aimed for admin usage / first use / setup / statistics - basically it allows you to call various sdk APIs from command line, and see the output on stdout without having to call API directly from code

when you are using iggy, you are required to have running server somewhere (you can host it anywhere) and you have to interact with it using library which is delivered to crates.io

regarding pub/sub, in principle we don't have it, but **in theory** you can implement it using iggy. in order to do that, you need to build consumer app, that will read stream and insert it to db or something like that, and other app which will write (append) data to the stream of consumer app

but I advise against it - there are better libraries for it - iggy is not a queue, so consumer has to navigate around the stream, so you don't get typical push notifications.

does that answer your question? :)

**Comment by Froidoh** [comment]
Yes it does, thank you very much and sorry for not making this a Discussion!
